### ISSUE TITLE
Probable Spelling Mistake for Version Number in README

### ISSUE THREAD

**Issue by MrMysterius** [Sidpatchy/InventoryRollback-Continued#6]
https://github.com/Sidpatchy/InventoryRollback-Continued/blob/f8440f57877a6ce0f2c843d585d28a1543489521/README.md?plain=1#L10

I think it should say 1.5.3 and not 2.5.3, because 2.5.3 doesn't exist yet.

**Comment by Sidpatchy** [comment]
See #7 

Good catch, thank you!
